

```{r 01000202setup, include=FALSE}

################################################################################
# PostData Statistics: 
# Fernando San Segundo, Marcos Marva
# Web: www.postdata-statistics.com
# Mail: postdatastatistics@gmail.com        (secondary: marcos.marva@gmail.es)
################################################################################

## 01000202 Cumulative frequencies from csv file.
```


```{r echo=FALSE, results='hide'}
## DATA GENERATION
signifDig <- 4

n = sample(100:500, 1)
data = c(sample(1:30, n, replace=TRUE))
(dataDF = data.frame(x=data))

(fileName = paste0("data", paste0(sample(c(LETTERS, 0:9), 10), collapse = ""), ".csv", collapse = ""))
write.table(dataDF, file = fileName, sep = " ", row.names = FALSE)

(cumfrequencies = cumsum(table(data)))
(orderedUniqueValues = sort(unique(data)))
frecTableForQuestion = cbind(orderedUniqueValues, signif(cumfrequencies, digits = signifDig))

(chooseValue = sample(data, 1))

## QUESTION/ANSWER GENERATION
(sol = unname(frecTableForQuestion[orderedUniqueValues == chooseValue, ][2]))

(sol = signif(sol, signifDig))
```


```{r eval=(language == "en"), echo=FALSE, results='hide'}
question=paste0("Construct the **cumulative frequency** table of the set of numbers in the attached file, and find the **cumulative frequency** of the value ", chooseValue, ".")

answer=paste0("The answer is ",
  sol
)

```


```{r eval=(language == "es"), echo=FALSE, results='hide'}
question = paste0(
"Construye la tabla de **frecuencias acumuladas** del conjunto de números del fichero adjunto y responde cuál es la **frecuencia acumulada** del número ", chooseValue, ".")

answer=paste0("La respuesta es ", sol)
```


Question
========

```{r results='asis', echo=FALSE}
cat(paste(question,collapse=""))
```

```{r results='asis', echo=FALSE}
cat(attachfile(fileName))
```


Solution
=========

```{r results='asis', echo=FALSE}
cat(paste(answer,collapse=""))
```

Meta-information
================
extype: num
exsolution: `r fmt(sol, signifDig)`
exname: 01000202
extol: 0.01


