
```{r 010101setup, include=FALSE}

################################################################################
# PostData Statistics: 
# Fernando San Segundo, Marcos Marva
# Web: www.postdata-statistics.com
# Mail: postdatastatistics@gmail.com        (secondary: marcos.marva@gmail.es)
################################################################################

## 010101 Relative frequencies from a list of integers.
```


```{r echo=FALSE, results='hide'}
## DATA GENERATION
signifDig <- 4

n = sample(15:20, 1)

data = c(sample(1:10, n, replace=TRUE))

(relFrequencies = unname(signif(table(data) / n, 4)))
(orderedUniqueValues = sort(unique(data)))
frecTableForQuestion = cbind(orderedUniqueValues, relFrequencies)

(chooseValue = sample(data, 1))

## QUESTION/ANSWER GENERATION
(sol = unname(frecTableForQuestion[orderedUniqueValues == chooseValue, ][2]))

(sol = signif(sol, signifDig))
```


```{r eval=(language == "en"), echo=FALSE, results='hide'}
question=paste0("Given the set of values $$", paste0(data, collapse = ", "),"$$ construct their **relative frequency** table, and find the **relative frequency** of the value ", chooseValue, ".")

answer=paste0("The answer is ",
  sol
)

```


```{r eval=(language == "es"), echo=FALSE, results='hide'}
question = paste0(
"Dados los valores  $$", paste0(data, collapse = ", "),"$$ construye su tabla de **frecuencias relativas** y responde cuál es la **frecuencia relativa** del número ", chooseValue, ".")

answer=paste0("La respuesta es ", sol)
```


Question
========

```{r results='asis', echo=FALSE}
cat(paste(question,collapse=""))
```

Solution
=========

```{r results='asis', echo=FALSE}
cat(paste(answer,collapse=""))
```

Meta-information
================
extype: num
exsolution: `r fmt(sol, signifDig)`
exname: 010101
extol: 0.01


