
```{r 01030402setup, include=FALSE}

################################################################################
# PostData Statistics: 
# Fernando San Segundo, Marcos Marva
# Web: www.postdata-statistics.com
# Mail: postdatastatistics@gmail.com        (secondary: marcos.marva@gmail.es)
################################################################################

## 01030402 Find the histogram that best describes the data in a given boxplot.
```


```{r echo=FALSE, results='hide'}
## DATA GENERATION
sample1=c(0,20,runif(50, 0,20),runif(50,1,5))
sample2=c(0,20,runif(30, 0,20), runif(35, 0,4),runif(35,16,20))
sample3=c(0,20,runif(50, 0,20),runif(50,7,13))

sampleList = list(sample1, sample2, sample3) 

## QUESTION/ANSWER GENERATION

sol = sample(1:3, 1)
solData = sampleList[[sol]]

k = 3 # Number of boxplots

solutions = rep(F, k)
solutions[sol] = T

if(language=='en'){
  histLabels = paste0("Sample ", 1:3)
  histYlabel = "Frequency"
  question = paste0("The boxplot describes the same data as one of the following histograms. Choose the right histogram.")
  } else if(language=='es'){
    histLabels = paste0("Muestra ", 1:3)
    histYlabel = "Frecuencia"
    question=paste0("El diagrama de caja y bigotes (boxplot) describe los mismos datos que uno de los histogramas. Elige el histograma correcto.")
  }


(binarySolution = paste0(as.numeric(solutions), collapse = ""))



```


Question
========

```{r results='asis', echo=FALSE}
cat(paste(question, collapse=""))
```


```{r boxplot, echo = FALSE, results = "hide", fig.height = 6, fig.width = 6, fig.path = "", fig.cap = ""}
par(mfrow=c(2,2))
boxplot(solData, xlab = "", main="",  horizontal = TRUE) 
hist(sample1, main = histLabels[1], xlab = "", ylab = histYlabel, xlim=c(min(solData), max(solData)))
hist(sample2, main = histLabels[2], xlab = "", ylab = histYlabel, xlim=c(min(solData), max(solData)))
hist(sample3, main = histLabels[3], xlab = "", ylab = histYlabel, xlim=c(min(solData), max(solData)))
par(mfrow=c(1,1))
```


Answerlist
----------

```{r results='asis', echo=FALSE}
cat(paste("* ", histLabels[1], collapse=""), fill = 1)
cat(paste("* ", histLabels[2], collapse=""), fill = 1)
cat(paste("* ", histLabels[3], collapse=""), fill = 1)
```




Solution
========

Answerlist
----------

```{r eval=(language == "es"), echo=FALSE, results='hide'}
solutions = ifelse(solutions, "Cierto", "Falso")
```



```{r results='asis', echo=FALSE}
cat(paste("* ", solutions[1], collapse=""), fill = 1)
cat(paste("* ", solutions[2], collapse=""), fill = 1)
cat(paste("* ", solutions[3], collapse=""), fill = 1)
```


Meta-information
================

```{r results='asis', echo=FALSE}
cat("exname: 01030402", fill = 1)
cat("extype: mchoice", fill = 1)
cat(paste0("exsolution: ", binarySolution, collapse = ""), fill = 1)
cat("exshuffle: FALSE", fill = 1)
```





