```{r echo=FALSE, eval=FALSE}

################################################################################
# PostData Statistics: 
# Fernando San Segundo, Marcos Marva
# Web: www.postdata-statistics.com
# Mail: postdatastatistics@gmail.com        (secondary: marcos.marva@gmail.es)
################################################################################

## ## 050101 Confidence interval for the mean, normal population, unknown variance, sample size > 30 (uses Z)
```


```{r data generation, echo = FALSE, results = "hide"}
signifDig = 4  

a = 0
b = 0

whichEnd = sample(c(0, 1), 1) 

while((min(abs(c(a, b))) < 0.00001)| (max(abs(c(a, b))) > 999)){

  (xbar = signif(runif(n = 1, min = -50, max = 50),  digits=3))
  (s = signif(runif(1, min = 0.1,max = 10), digits=3))
  (n = sample(100:250, 1))
  (confLevel = sample(c(0.9, 0.95, 0.99), 1))
  (alfa = 1 - confLevel)

  
  # calculate the critical value
  (z_alfa2 = qnorm(1 - alfa / 2))
  
  # calculate the half length of the confidence interval
  halfLength = z_alfa2 * s / sqrt(n)
  
  # the confidence interval is
  # lower end
  (a = xbar - halfLength)
  
  # upper end
  (b = xbar + halfLength)
  
}

(solution = signif(ifelse(whichEnd == 0, a, b), digits = signifDig))

(solutionString01 = paste0("(", signif(a, digits = signifDig), ", ", signif(b, digits = signifDig), ")"))



sol = solution
```


```{r eval=(language == "en"), echo=FALSE, results='hide'}
(solutionString02 = ifelse(whichEnd == 0, "left", "right"))

(question=paste0("$X$ is a normal random variable.  Given a random sample of length $", n,"$ with sample mean $\\bar{X} = ", xbar,"$ and  sample standard deviation $s=", s,"$ assume that the sample is large and find the ", solutionString02 ," endpoint of a confidence interval $(a,\\,b)$ for the mean $\\mu_X$, with a confidence level $", 100 * confLevel, "$%.  
Use ", signifDig, "  significant digits in your answer."))

(answer=paste0("With $\\alpha = ", alfa, "$ the confidence interval is $$\\bar X\\pm z_{\\alpha/2}\\dfrac{s}{\\sqrt{n}} = ", xbar,"\\pm ", fmt(z_alfa2, 3), "\\dfrac{", s,"}{\\sqrt{", n,"}} = " , solutionString01, "$$ and the solution is ", sol, "."))
```



```{r eval=(language == "es"), echo=FALSE, results='hide'}
(solutionString02 = ifelse(whichEnd == 0, "izquierdo", "derecho"))


(question=paste0("La variable aleatoria $X$ es normal. Se ha obtenido una muestra de tamaño $", n, "$, con media muestral $\\bar{X} = ", xbar,"$ y cuasidesviación típica $s = ", s, "$. Asumiendo que se trata de una muestra de tamaño grande, calcula el extremo ", solutionString02 ," de un intervalo de confianza $(a,\\, b)$ para la media $\\mu_X$, con un nivel de confianza del $",100 * confLevel, "$\\%.  
Utiliza ", signifDig, " cifras significativas en tu respuesta."))
  
(answer=paste0("Con $\\alpha = ", alfa, "$ el intervalo es $$\\bar X\\pm z_{\\alpha/2}\\dfrac{s}{\\sqrt{n}} = ", xbar,"\\pm ", fmt(z_alfa2, 3), "\\dfrac{", s,"}{\\sqrt{", n,"}} = " , solutionString01, "$$ así que la respuesta es ", sol, "."))
```



Question
========

```{r results='asis', echo=FALSE}
cat(paste(question,collapse=""))
```


Solution
=========

```{r results='asis', echo=FALSE}
cat(paste(answer,collapse=""))
```

Meta-information
================
extype: num
exsolution: `r fmt(abs(sol), 3)`
exname: 050101
extol: 0.01