---
title: "ExamineR Project. Exercise List, 2018 version."
author: "Fernando San Segundo."
date: 'Last update: `r format(Sys.time(), "%Y-%m-%d")`'
output:
  html_document:
    toc: yes
    toc_depth: 2
  pdf_document:
    toc: yes
    toc_depth: '2'
---

```{r echo=FALSE, eval=FALSE}
https://github.com/PostDataStatistics/ExamineR/tree/RmdExams2
git push origin RmdExams2
```

# 01 Descriptive statistics

## 0100 Frequency tables.

+ 01000001 ->- Absolute frequencies from set of integer values.
+ 01000002 ->- Absolute frequencies from csv file.
+ 01000101 ->- Relative frequencies from set of integer values.
+ 01000102 ->- Relative frequencies from csv file.
+ 01000201 ->- Cumulative frequencies from set of integer values.
+ 01000202 ->- Cumulative frequencies from csv file.
+ 01000301 ->- Multiple choice, properties of absolute, relative, cumulative frequencies..

## 0101 Central Values.

+ 01010001 ->- Arithmetic mean for a set of integer values.
+ 01010002 ->- Arithmetic mean for a csv file of integer values.

+ 01010101 ->- Arithmetic mean from a table of absolute frequencies.
+ 01010102 ->- Arithmetic mean from a table of relative frequencies.

+ 01010201 ->- Median of a set of integer values.
+ 01010202  ->- Median from csv file.

## 0102 Dispersal. Variances and Standard Deviations for population and Sample.

+ 01020101 ->- Population variance for a set of integer values.
+ 01020102 ->- Population variance for a csv file of integer values. 
+ 01020103 ->- Population variance from a table of absolute frequencies.
+ 01020104 ->- Population variance from a table of relative frequencies.

+ 01020201 ->- Population standard deviation for a set of integer values.
+ 01020202 ->- Population standard deviation for a csv file of integer values. 
+ 01020203 ->- Population standard deviation from a table of absolute frequencies.
+ 01020204 ->- Population standard deviation from a table of relative frequencies.

+ 01020301 ->- Sample variance for a set of integer values.
+ 01020302 ->- Sample variance for a csv file of integer values. 
+ 01020303 ->- Sample variance from a table of absolute frequencies.
+ 01020304 ->- Sample variance from a table of relative frequencies.

+ 01020401 ->- Sample standard deviation for a set of integer values.
+ 01020402 ->- Sample standard deviation for a csv file of integer values. 
+ 01020403 ->- Sample standard deviation from a table of absolute frequencies.
+ 01020404 ->- Sample standard deviation from a table of relative frequencies.

## 0103 Exploratory Graphics. 

+ 01030401 ->- Find the boxplot that best describes the data in a given histogram.
+ 01030402 ->- Find the histogram that best describes the data in a given boxplot.
+ 01030403 ->- Find the density curve that best describes the data in a given boxplot.

### 010303 Boxplots.

+ 01030301 ->- Identify outliers in the data from a csv file. 



# 05 Confidence Intervals.

## 0501 CI for the Mean, Normal Population.

+ 050101 ->- Confidence interval for the mean, normal population, large sample size >100 (uses normal Z distribution).
+ 050201 ->- Confidence interval for the mean, normal population, small sample size < 30 (uses Student t distribution).
+ 050301 ->- Confidence interval for the standard deviation, sample from a normal population.